name: Scheduler

on:
  schedule:
    - cron:  '50 8 * * *'
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Compile
      run: gcc *.c -lm -o cloudgen
    - name: Generate cloud
      run: ./cloudgen
    - name: Commit files
      run: |
        git config --local user.email "wancom@github"
        git config --local user.name "wancom"
        git add .
        git commit -m "Update"
        git remote -v
        git pull origin master
        git push origin master