name: Scheduler

on:
  schedule:
    - cron:  '0 22 * * *'
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Compile
      run: gcc *.c -lm -o cloudgen
    - name: Generate cloud
      run: ./cloudgen
    - name: Convert image and update
      run: |
        convert *.bmp docs/latest.png
        cp docs/latest.png png/`date +%s`.png
        sed -i -e "s/Latest update: .*/Latest update: `date`/g" docs/index.html
    - name: Commit files
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "wancom@github"
        git config --local user.name "wancom"
        git remote set-url origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git fetch
        git checkout master
        git pull origin master
        git add png docs
        git commit -m "Update"
        git push origin master