name: Scheduler

on:
  schedule:
    - cron:  '10 11 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Compile
      run: gcc *.c -lm -o cloudgen
    - name: Generate cloud
      run: ./cloudgen
    # - name: Install tools
    #   run: sudo apt update && sudo apt install -y imagemagick</dev/null
    - name: Convert image
      run: convert *.bmp png/`date +%s`.png
    - name: Commit files
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "wancom@github"
        git config --local user.name "wancom"
        git remote set-url origin https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        git fetch
        git checkout master
        git pull origin master
        git add png
        git commit -m "Update"
        git push origin master